### ISSUE TITLE
Pass Parameters to the Kernel Using GRUB Command Line

### ISSUE THREAD

**Issue by turbolay** [ppenna/nanvix#107]
**Description**

The idea is to be able to pass parameters to the kernel using the GRUB menu. We can do it with the command-line parameter provided by GRUB in the command kernel, file menu.lst (Documentation: https://ftp.gnu.org/old-gnu/Manuals/grub/html_node/kernel.html). 
Here's an example of a file doing so:

```
timeout 10

title	Nanvix
	root (fd0)
	kernel /kernel
	module /initrd.img

title	Nanvix-debug
	root (fd0)
	kernel /kernel 001
	module /initrd.img
```
This information should be accessible in the boot.S file, using an offset of 16 on _EBX_ (as it's done for initrd with an offset on 24), (Documentation: https://www.gnu.org/software/grub/manual/multiboot/multiboot.html#Specification)

However, the argument can't be accessed that way.
Furthermore, the flag[2] of _EBX_ (accessible with an offset of 0) is always set to 1, no matter if a command-line argument was provided

**Comment by Theldus** [comment]
Hello @turbolay 
> This information should be accessible in the boot.S file, using an offset of 16 on EBX (as it's done for initrd with an offset on 24)

In fact it is accessible, keep in mind that _EBX_ stores the pointer to the mb_info structure, and offset 16 of the structure stores a pointer to the region that actually stores the string.

So try to do something like: (DDD console)
*All the commands below can be done using the graphical features of the DDD, but it would be harder to explain ;-)
```
(gdb) b start
(gdb) c
-- wait for machine pauses --
(gdb) info registers ebx (shows the value of ebx)
ebx            0x2b920	178464

(gdb) x /10xw $ebx       (shows the first ten values word sized (4 bytes) in hexadecimal, pointed to by ebx.)
0x2b920:	0x000007ef	0x0000027f	0x0003fb80	0xe0ffffff
0x2b930:	0x00002000	0x00000001	0x00020740	0x00000009
0x2b940:	0x00000028	0x00147000

Ok, so the cmdline field has the value 0x00002000, let's see what we have there:

(gdb) x /10sb 0x00002000 (displays the first 10 strings pointed to by address 0x00002000)
0x2000:	"/kernel some_parameter"
0x2017:	"/initrd.img"
0x2023:	""
-- cut --
0x202a:	""
```
So you can access the field, you just need to copy that portion of memory if you want to process it in some other portion of the kernel : D.

> Furthermore, the flag[2] of EBX (accessible with an offset of 0) is always set to 1, no matter if a command-line argument was provided

Yes, it is true, I believe that GRUB assumes that it will always have some portion of string to be displayed as a command line so it always activates this flag, as you can see [here](https://github.com/Theldus/GRUB-Legacy/blob/0.96/grub/stage2/common.c#L317), line 317, flag _MB_INFO_CMDLINE_.

----
Sorry for the big answer but I believe I have helped.

**Comment by turbolay** [comment]
It helped a lot and actually resolved the issue. The key was to understand that $ebx was storing adresses instead of values. Thank you
