### ISSUE TITLE
[doc] Inconsistency in timeout parameter

### ISSUE THREAD

**Issue by LucasGdosR** [ppenna/nanvix#327]
## Description

Default arguments on Makefile are leading to timeout when running in QEMU.

In `run.md`:
> ```bash
> # Run Nanvix in QEMU with default parameters:
> # make TARGET=x86 LOG_LEVEL=warn MACHINE=qemu-pc TIMEOUT=90 run
> make run
> ```
TIMEOUT=90 is the expected argument

However, in `Makefile`:
> ```bash
> # Timeout
> export TIMEOUT ?= 10
> ```

TIMEOUT=10 leads to errors when running `make run`:
> passed test_mmap_write_munmap
> running memory management daemon (pid=2)...
> acquiring exception management capability...
> subscribing to page faults...
> qemu-system-i386: terminating on signal 2 from pid 46620 (timeout)

## How to Reproduce
Follow the tutorial using a hard disk drive. SSD probably won't run into the issue.

## Expected Behavior
The tests should have a long enough timeout so it only crashes if something is definitely wrong. For me using a HDD, 20 was enough, and 15 wasn't.

**Comment by ppenna** [comment]
@LucasGdosR this is not a bug, as the default timeout is intentionally calibrated for the CI infrastructure and you one can override that value via command-line:

```bash
make TIMEOUT=120 run
```

You are welcomed to submit a PR on the [run.md](https://github.com/nanvix/nanvix/blob/02179c58c3fa2b12f01b11a2873147c1195c03c1/doc/run.md) documentation to add a note on this:

```
...
TIMEOUT=<seconds>: Set the timeout for the run script. You may want to override the default value if your development environment is a low-end machine (ie: old CPU, HDD disk, low RAM).
...
```
