### ISSUE TITLE
Child process don't die in fork()

### ISSUE THREAD

**Issue by Theldus** [ppenna/nanvix#36]
<b>Description</b>
Using the fork() system call, both processes run until the end, but the child process becomes zombie and don't die.

<b>Reproducing the Problem</b>
Just compile and execute the following code:
```c
#include <unistd.h>
int main()
{
	fork();
	return 0;
}
```
and check the list of running processes calling the ps program.

**Comment by ppenna** [comment]
I'll check it.

**Comment by ppenna** [comment]
Bug confirmed.

It seems to be a problem in the wait() system call.

**Comment by ppenna** [comment]
Bug fixed on commit 58ca2abc8f37f4adf921e2d732fc15ffbb215f5b.

The problem was that INIT was adopting orphaned processes but it was not getting wakeup.
