### ISSUE TITLE
Updating toolchain & VM to latest

### ISSUE THREAD

**Issue by rurtle** [ppenna/nanvix#38]
Check what's the latest version of GCC (5.3.0 ATM) cross compiler compatible with latest binutils (2.25) version. Get it to work and update relevant script(s).

**Comment by rurtle** [comment]
Primary investigation shows that binutils v2.25 is compatible with latest gcc (v5.3.0) offerings. Compiled bochs without any hassle. Need to test it for overall Nanvix build though. Once done, will send a pull request.

**Comment by rurtle** [comment]
With the latest version of binutils & gcc, I was able to build Nanvix & boot it just fine. Not sure of other implications though.

**Comment by ppenna** [comment]
Check commit 8977980a4574a3bde8ab1489581a44918d42e270
