### ISSUE TITLE
Fix Command History in TSH

### ISSUE THREAD

**Issue by ppenna** [ppenna/nanvix#41]
**Description**

Command history in TSH is buggy. If you type some commands and arbitrarily hit the up/down key you'll notice an unexpected behavior.

**Starting Point**

Debug and enhance the current implementation.

**Comment by Theldus** [comment]
It's probably my fault, I can work on that, but why two stacks?

**Comment by ppenna** [comment]
Hey Theldus, not a big problem... I opened this issue because Subhra wanted to start contributing with small fixes and he will handle this ;-)

**Comment by ppenna** [comment]
Bug partially fixed in commit 19c0c562e0ce061cf82af93ccbfd077c9888f28f by @rurtle

**Comment by ppenna** [comment]
Bug fixed in commit 064aea436107b40c453f5907d07b6b0f3711c2bb.
