### ISSUE TITLE
Protection fault when implementing mini regions.

### ISSUE THREAD

**Issue by Theldus** [ppenna/nanvix#48]
**Description:**
The init process becomes zombie after an 'execve' syscall due to protection fault in user stack, at address 0xbffffe8.

**Comment by ppenna** [comment]
@Theldus can you somehow reproduce this problem when not using your implementation?

We should track the source of the problem. This bug may come from the hard disk driver or the miniregion implementation

**Comment by Theldus** [comment]
I can try, but I think there's a problem with miniregion implementation, I need to investigate better, I'll keep you informed for any news.

**Comment by Theldus** [comment]
This bug was fixed a while ago and a working version of miniregions can be found in the commit a3c1d75
