### ISSUE TITLE
Full Time & Date Support

### ISSUE THREAD

**Issue by ppenna** [ppenna/nanvix#49]
**Description**

Read at startup the current date and time, so that we can correctly keep track of this information. 

**Starting Point**

Write a driver for accessing the CMOS device to query the required information.

More information at: http://wiki.osdev.org/CMOS

**Comment by ppenna** [comment]
Assigned to @rurtle.

**Comment by rurtle** [comment]
Sent pull request for CMOS driver implementation.

**Comment by ppenna** [comment]
@rurtle  I've just merged your pull request in the 'dev' branch.

Commit 0a662cf8b03aa0821baf08cef0148a267bcd3d6b
